### ISSUE TITLE
Trying to Add Recaptcha 

### ISSUE THREAD

**Issue by fyrftr72** [formtools/core#196]
Hi Ben, I have followed the guide here: https://docs.formtools.org/api/v2/display_captcha
as close as possible. I keep getting this error: 
**600 | User | The public and/or private recaptcha field key hasn't _been set in your api.php file._ For more information, read the instructions on the 	displayCaptcha() page**.

Since I have added the recaptcha keys to the: global/config.php, file as directed in the guide, but the error says it must be added to "api.php" file, I cannot see how to do that.

I am working with a fresh install of FT 3.xx and  a new form that is finalized and is working perfectly.

Thanks, Gene

**Comment by benkeen** [comment]
Hi @fyrftr72, sorry for the wait! 

I've just fixed that incorrect line in the documentation & I'll update that on the live site soon. It wasn't right: adding those two settings to your `global/config.php` is all you should need to do to get the captcha to show up. 

Hmm... I must say the code looks fine... I don't suppose it's possible for you to share your form with me (the PHP code)? I'm curious to see if there's anything special about it that's causing this error...  If so, email me at ben.keen@gmail with it so I can take a look. 

You're not doing this line before your `new FormTools\API()` line, I assume?

```php
Core::init();
```

**Comment by benkeen** [comment]
Hey @fyrftr72, I'm so sorry for not getting back to you sooner. Will look at now.

**Comment by fyrftr72** [comment]
To satisfy my client, I enabled the client side captcha, so it is still not the server side using the form tools API sorry for the confusion. 

Based on your response, I removed the second API and it is now working!
Thank you so much for your response and for Form Tools!

Gene Wilson

**Comment by benkeen** [comment]
No problem, glad to help. :)
